language: c

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
    - secure: "Rv43iXO0lp/aNy39JG+epWNXCMuNWTp2niLD4UHTfil/JOuTIbpIg8diMtSDa0ifeQklepVrsS9qv4MDxvFfVCRCwsOm+trUhgKImQ3fR2qpsv2CUXkpBCRuWEq8qMw6ljoioxe/S5354zlOorqbRf1+n+J5KopKlvFFSnYEumA="

script:

  - echo travis_fold:start:AUTORECONF
  - autoreconf --install
  - echo travis_fold:end:AUTORECONF

  - echo travis_fold:start:CONFIGURE
  - ./configure
  - echo travis_fold:end:CONFIGURE

  - echo travis_fold:start:MAKE
  - make
  - echo travis_fold:end:MAKE

  - echo travis_fold:start:TESTS
  - make check
  - echo travis_fold:end:TESTS

  - echo travis_fold:start:COVERAGE
  - gcov src/e4c.c --object-file test/test_e4c-e4c
  - echo travis_fold:end:COVERAGE

after_success:

  - bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "guillermocalvo/exceptions4c"
      description: "An exception handling framework for C"
    notification_email: coverity@guillermo.in
    build_command_prepend: "./configure; make clean"
    build_command: "make -j 4"
    branch_pattern: master
